spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        show_sql: true
logging:
  file:
    name: log/paycraft-service-dev.log
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 6020
  error:
    include-message: always